server:
 port: 8080


spring:
  application:
    name: quiz-app-backend
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
   console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
